# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    App\EventListener\AdresseListener:
        tags:
            -
                # Ces 3 options sont nécessaires pour que ça fonctionne
                name: 'doctrine.orm.entity_listener'
                # Par défaut, le nom de la méthode appelée = nom de l'event
                event: 'prePersist'
                entity: 'App\Entity\User'
                # On peut indiquer le nom de la méthode si différente de l'event
                method: 'fetchLongitude''fetchLatitude'
            -
                # Ces 3 options sont nécessaires pour que ça fonctionne
                name: 'doctrine.orm.entity_listener'
                # Par défaut, le nom de la méthode appelée = nom de l'event
                event: 'preUpdate'
                entity: 'App\Entity\User'
                # On peut indiquer le nom de la méthode si différente de l'event
                method: 'userAdresse'
